#!/usr/bin/env python3
"""Emit src/ui/panels/PanelRegistry.qml — large AE-style panel catalog for the editor."""
from __future__ import annotations

from pathlib import Path

# First 29 entries must stay in sync with wired Loader cases in EditorWindow.qml (ids 0–28).
WIRED: list[tuple[str, str]] = [
    ("Project", "Media & Assets"),
    ("Media Pool", "Media & Assets"),
    ("Media Browser", "Media & Assets"),
    ("Library", "Media & Assets"),
    ("Footage Info", "Media & Assets"),
    ("Metadata", "Media & Assets"),
    ("Effects & Presets", "Effects"),
    ("Effect Controls", "Effects"),
    ("Transitions", "Effects"),
    ("Essential Graphics", "Effects"),
    ("Content-Aware Fill", "Effects"),
    ("Color", "Color"),
    ("Lumetri Scopes", "Color"),
    ("Character", "Text"),
    ("Paragraph", "Text"),
    ("Motion Sketch", "Animation"),
    ("Graph Editor", "Animation"),
    ("Mask Interpolation", "Animation"),
    ("Smoother", "Animation"),
    ("Tracker", "3D & Tracking"),
    ("3D Transform", "3D & Tracking"),
    ("Flowchart", "3D & Tracking"),
    ("Audio Mixer", "Audio"),
    ("Align", "Layout"),
    ("Markers", "Layout"),
    ("History", "Layout"),
    ("Render Queue", "Output"),
    ("Inspector", "Layout"),
    ("Info", "Layout"),
]

# Additional catalog entries (placeholders — same chrome as PanelPlaceholder).
EXTRA: list[tuple[str, str]] = [
    ("Composition", "Composition"),
    ("Composition Settings", "Composition"),
    ("Layer", "Composition"),
    ("Pre-compose", "Composition"),
    ("Guide Layers", "Composition"),
    ("Camera", "3D & Tracking"),
    ("Light", "3D & Tracking"),
    ("Null Object", "3D & Tracking"),
    ("Cinema 4D", "3D & Tracking"),
    ("Ray-traced 3D", "3D & Tracking"),
    ("Classic 3D", "3D & Tracking"),
    ("Material Options", "3D & Tracking"),
    ("Environment", "3D & Tracking"),
    ("Paint", "Paint & Clone"),
    ("Brushes", "Paint & Clone"),
    ("Clone Stamp", "Paint & Clone"),
    ("Roto Brush", "Paint & Clone"),
    ("Refine Edge", "Paint & Clone"),
    ("Content-Aware Fill Options", "Paint & Clone"),
    ("Audio Waveform", "Audio"),
    ("Audio Spectrum", "Audio"),
    ("Audio Levels", "Audio"),
    ("Loudness Radar", "Audio"),
    ("Parametric EQ", "Audio"),
    ("Dynamics", "Audio"),
    ("Multiband Compressor", "Audio"),
    ("DeNoise", "Audio"),
    ("DeReverb", "Audio"),
    ("Lumetri Color", "Color"),
    ("Scopes", "Color"),
    ("Vectorscope", "Color"),
    ("Waveform (Luma)", "Color"),
    ("Parade (RGB)", "Color"),
    ("Histogram", "Color"),
    ("False Color", "Color"),
    ("HDR Scopes", "Color"),
    ("HDR Monitoring", "Color"),
    ("OCIO Color Management", "Color"),
    ("LUT Browser", "Color"),
    ("Curves", "Color"),
    ("Color Wheels", "Color"),
    ("HSL Secondary", "Color"),
    ("Vignette", "Color"),
    ("Sharpen", "Color"),
    ("Film Grain", "Color"),
    ("Creative Look", "Color"),
    ("Basic Correction", "Color"),
    ("Input LUT", "Color"),
    ("Output LUT", "Color"),
    ("Scopes Overlay", "Color"),
    ("Safe Margins", "Preview"),
    ("Title / Action Safe", "Preview"),
    ("Grid & Guides", "Preview"),
    ("Rulers", "Preview"),
    ("Snap", "Preview"),
    ("Timecode", "Preview"),
    ("Audio Time Units", "Preview"),
    ("Proxy Workflow", "Media & Assets"),
    ("Ingest", "Media & Assets"),
    ("Watch Folders", "Media & Assets"),
    ("Team Projects", "Media & Assets"),
    ("Production", "Media & Assets"),
    ("Sync Settings", "Media & Assets"),
    ("Keyboard Shortcuts", "Layout"),
    ("Workspace", "Layout"),
    ("Tools", "Layout"),
    ("Progress", "Output"),
    ("Audio Hardware", "Audio"),
    ("Audio Mapping", "Audio"),
    ("Audio Track Mixer", "Audio"),
    ("Submix", "Audio"),
    ("Master", "Audio"),
    ("Essential Sound", "Audio"),
    ("Speech to Text", "Audio"),
    ("Captions", "Text"),
    ("Graphics Templates", "Text"),
    ("Motion Graphics", "Text"),
    ("Responsive Design", "Text"),
    ("Font Browser", "Text"),
    ("OpenType", "Text"),
    ("SVG Support", "Text"),
    ("Advanced Text", "Text"),
    ("Paragraph Styles", "Text"),
    ("Character Styles", "Text"),
    ("Mocha AE", "3D & Tracking"),
    ("3D Camera Tracker", "3D & Tracking"),
    ("Warp Stabilizer", "3D & Tracking"),
    ("Rolling Shutter Repair", "3D & Tracking"),
    ("Timewarp", "Animation"),
    ("Time Remapping", "Animation"),
    ("Posterize Time", "Animation"),
    ("Frame Blending", "Animation"),
    ("Pixel Motion Blur", "Animation"),
    ("CC Force Motion Blur", "Animation"),
    ("Interpret Footage", "Media & Assets"),
    ("Replace Footage", "Media & Assets"),
    ("Reveal in Explorer", "Media & Assets"),
    ("Consolidate All", "Media & Assets"),
    ("Collect Files", "Media & Assets"),
    ("Dependencies", "Media & Assets"),
    ("Project Manager", "Media & Assets"),
    ("Flowchart View", "Composition"),
    ("Mini-Flowchart", "Composition"),
    ("Layer Navigator", "Composition"),
    ("Solo / Hide", "Composition"),
    ("Shy Layers", "Composition"),
    ("Quality", "Preview"),
    ("Resolution", "Preview"),
    ("Adaptive Preview", "Preview"),
    ("Fast Previews", "Preview"),
    ("GPU Info", "Output"),
    ("Memory", "Output"),
    ("Disk Cache", "Output"),
    ("Media Cache", "Output"),
    ("Database", "Output"),
    ("Autosave", "Output"),
    ("Versioning", "Output"),
    ("Render Settings", "Output"),
    ("Output Module", "Output"),
    ("Best Settings", "Output"),
    ("Draft Settings", "Output"),
    ("Custom Template", "Output"),
    ("Network Render", "Output"),
    ("Adobe Media Encoder", "Output"),
    ("AME Presets", "Output"),
    ("Simulation", "Effects"),
    ("Particle Systems", "Effects"),
    ("Physics", "Effects"),
    ("Force Field", "Effects"),
    ("Wind", "Effects"),
    ("Turbulence", "Effects"),
    ("Distort", "Effects"),
    ("Mesh Warp", "Effects"),
    ("Liquify", "Effects"),
    ("Bulge", "Effects"),
    ("Twirl", "Effects"),
    ("Ripple", "Effects"),
    ("Displacement Map", "Effects"),
    ("Offset", "Effects"),
    ("Motion Tile", "Effects"),
    ("CC Bend It", "Effects"),
    ("CC Blobbylize", "Effects"),
    ("CC Flo Motion", "Effects"),
    ("CC Griddler", "Effects"),
    ("CC Page Turn", "Effects"),
    ("CC Power Pin", "Effects"),
    ("CC Slant", "Effects"),
    ("CC Smear", "Effects"),
    ("CC Split", "Effects"),
    ("CC Split 2", "Effects"),
    ("CC Tiler", "Effects"),
    ("CC Vector Blur", "Effects"),
    ("Bezier Warp", "Effects"),
    ("Corner Pin", "Effects"),
    ("Magnify", "Effects"),
    ("Mirror", "Effects"),
    ("Optics Compensation", "Effects"),
    ("Reshape", "Effects"),
    ("Spherize", "Effects"),
    ("Transform", "Effects"),
    ("Turbulent Displace", "Effects"),
    ("Wave Warp", "Effects"),
    ("Stylize", "Effects"),
    ("Brush Strokes", "Effects"),
    ("Cartoon", "Effects"),
    ("Color Emboss", "Effects"),
    ("Emboss", "Effects"),
    ("Find Edges", "Effects"),
    ("Glow", "Effects"),
    ("Mosaic", "Effects"),
    ("Motion Tile Stylize", "Effects"),
    ("Scatter", "Effects"),
    ("Strobe Light", "Effects"),
    ("Texturize", "Effects"),
    ("Threshold", "Effects"),
    ("Write-on", "Effects"),
    ("Generate", "Effects"),
    ("4-Color Gradient", "Effects"),
    ("Audio Spectrum Gen", "Effects"),
    ("Audio Waveform Gen", "Effects"),
    ("Beam", "Effects"),
    ("Cell Pattern", "Effects"),
    ("Checkerboard", "Effects"),
    ("Circle", "Effects"),
    ("Ellipse", "Effects"),
    ("Eyedropper Fill", "Effects"),
    ("Fill", "Effects"),
    ("Fractal", "Effects"),
    ("Grid", "Effects"),
    ("Lens Flare", "Effects"),
    ("Lightning", "Effects"),
    ("Radio Waves", "Effects"),
    ("Ramp", "Effects"),
    ("Stroke", "Effects"),
    ("Vegas", "Effects"),
    ("Blur & Sharpen", "Effects"),
    ("Box Blur", "Effects"),
    ("Camera Lens Blur", "Effects"),
    ("Channel Blur", "Effects"),
    ("Compound Blur", "Effects"),
    ("Directional Blur", "Effects"),
    ("Fast Box Blur", "Effects"),
    ("Gaussian Blur", "Effects"),
    ("Lens Blur", "Effects"),
    ("Radial Blur", "Effects"),
    ("Sharpen", "Effects"),
    ("Smart Blur", "Effects"),
    ("Unsharp Mask", "Effects"),
    ("Channel", "Effects"),
    ("Arithmetic", "Effects"),
    ("Blend", "Effects"),
    ("Calculations", "Effects"),
    ("Channel Combiner", "Effects"),
    ("Channel Mixer", "Effects"),
    ("Invert", "Effects"),
    ("Minimax", "Effects"),
    ("Remove Color Matting", "Effects"),
    ("Set Channels", "Effects"),
    ("Set Matte", "Effects"),
    ("Shift Channels", "Effects"),
    ("Solid Composite", "Effects"),
    ("Keying", "Effects"),
    ("Color Difference Key", "Effects"),
    ("Color Key", "Effects"),
    ("Color Range", "Effects"),
    ("Difference Matte", "Effects"),
    ("Extract", "Effects"),
    ("Inner/Outer Key", "Effects"),
    ("Key Cleaner", "Effects"),
    ("Keylight", "Effects"),
    ("Linear Color Key", "Effects"),
    ("Luma Key", "Effects"),
    ("Spill Suppressor", "Effects"),
    ("Matte Choker", "Effects"),
    ("Simple Choker", "Effects"),
    ("Matte Utilities", "Effects"),
    ("Noise & Grain", "Effects"),
    ("Add Grain", "Effects"),
    ("Dust & Scratches", "Effects"),
    ("Fractal Noise", "Effects"),
    ("Match Grain", "Effects"),
    ("Median", "Effects"),
    ("Noise", "Effects"),
    ("Noise HLS", "Effects"),
    ("Noise HLS Auto", "Effects"),
    ("Remove Grain", "Effects"),
    ("Turbulent Noise", "Effects"),
    ("Perspective", "Effects"),
    ("3D Glasses", "Effects"),
    ("Bevel Alpha", "Effects"),
    ("Bevel Edges", "Effects"),
    ("Drop Shadow", "Effects"),
    ("Radial Shadow", "Effects"),
    ("Time", "Effects"),
    ("Echo", "Effects"),
    ("Posterize", "Effects"),
    ("Timecode Overlay", "Effects"),
    ("Time Displacement", "Effects"),
    ("Transition Completion", "Effects"),
    ("Utility", "Effects"),
    ("Apply Color LUT", "Effects"),
    ("Cineon Converter", "Effects"),
    ("Color Profile Converter", "Effects"),
    ("Grow Bounds", "Effects"),
    ("HDR Compander", "Effects"),
    ("HDR Highlight Compression", "Effects"),
    ("Paint Bucket", "Effects"),
    ("Procedural", "Effects"),
    ("VR", "Effects"),
    ("VR Converter", "Effects"),
    ("VR Digital Glitch", "Effects"),
    ("VR Rotate Sphere", "Effects"),
    ("VR Sharpen", "Effects"),
    ("VR Chromatic Aberrations", "Effects"),
    ("VR Plane to Sphere", "Effects"),
    ("VR Sphere to Plane", "Effects"),
    ("Obsolete", "Effects"),
    ("Obsolete Path Text", "Effects"),
    ("Obsolete Basic 3D", "Effects"),
    ("AI Auto Brush", "AI"),
    ("AI Scene Edit", "AI"),
    ("AI Depth", "AI"),
    ("AI Rotoscope Assist", "AI"),
    ("AI Upscale", "AI"),
    ("AI Denoise (Video)", "AI"),
    ("AI Frame Interpolation", "AI"),
    ("AI Color Match", "AI"),
    ("AI Lighting", "AI"),
    ("AI Relight", "AI"),
    ("AI Object Mask", "AI"),
    ("AI Sky Replace", "AI"),
    ("AI Portrait", "AI"),
    ("AI Audio Clean", "AI"),
    ("AI Music Stem", "AI"),
    ("AI Transcription", "AI"),
    ("AI Translation", "AI"),
    ("AI Mood Board", "AI"),
    ("AI Storyboard", "AI"),
    ("AI Camera Path", "AI"),
    ("AI 3D Layout", "AI"),
    ("AI Material", "AI"),
    ("AI Texture", "AI"),
    ("AI Vectorize", "AI"),
    ("AI SVG Trace", "AI"),
    ("AI HDR Merge", "AI"),
    ("AI Exposure Fusion", "AI"),
    ("AI Green Screen", "AI"),
    ("AI Beauty", "AI"),
    ("AI Sharpen", "AI"),
    ("AI Deblur", "AI"),
    ("AI Super Slo-Mo", "AI"),
    ("AI Motion Smear", "AI"),
    ("AI Style Transfer", "AI"),
    ("AI Palette", "AI"),
    ("AI Grade from Reference", "AI"),
    ("AI Auto Levels", "AI"),
    ("AI Auto Contrast", "AI"),
    ("AI Histogram EQ", "AI"),
    ("AI Face Track", "AI"),
    ("AI Body Track", "AI"),
    ("AI Hand Track", "AI"),
    ("AI Planar Track", "AI"),
    ("AI Spline Track", "AI"),
    ("AI Point Track", "AI"),
    ("AI Stabilize", "AI"),
    ("AI Rolling Shutter", "AI"),
    ("AI Lens Profile", "AI"),
    ("AI Fisheye Remove", "AI"),
    ("AI Vignette Match", "AI"),
    ("AI Grain Match", "AI"),
    ("AI Halation", "AI"),
    ("AI Bloom", "AI"),
    ("AI Glitch Pack", "AI"),
    ("AI Datamosh", "AI"),
    ("AI Pixel Sort", "AI"),
    ("AI ASCII", "AI"),
    ("AI CRT", "AI"),
    ("AI VHS", "AI"),
    ("AI Film Damage", "AI"),
    ("AI Light Leak Pack", "AI"),
    ("AI Lens Dirt", "AI"),
    ("AI Anamorphic", "AI"),
    ("AI Chromatic", "AI"),
    ("AI Duotone", "AI"),
    ("AI Split Tone", "AI"),
    ("AI Film Print", "AI"),
    ("AI Print LUT", "AI"),
    ("AI ACES", "AI"),
    ("AI RCM", "AI"),
    ("AI Gamut Warning", "AI"),
    ("AI Legalize Broadcast", "AI"),
    ("AI Loudness", "AI"),
    ("AI True Peak", "AI"),
    ("AI LUFS Meter", "AI"),
    ("AI Phase Scope", "AI"),
    ("AI Goniometer", "AI"),
    ("AI Correlation", "AI"),
    ("AI Spectrogram", "AI"),
    ("AI Oscilloscope", "AI"),
    ("AI Loudness History", "AI"),
    ("AI Batch Queue", "AI"),
    ("AI Render Presets", "AI"),
    ("AI Export Suggest", "AI"),
    ("AI Proxy Policy", "AI"),
    ("AI Ingest Rules", "AI"),
    ("AI Metadata Tag", "AI"),
    ("AI Scene Detect", "AI"),
    ("AI Shot Classify", "AI"),
    ("AI Beat Detect", "AI"),
    ("AI Cut Suggest", "AI"),
    ("AI B-Roll Suggest", "AI"),
    ("AI Title Suggest", "AI"),
    ("AI Lower Third", "AI"),
    ("AI Caption Style", "AI"),
    ("AI Kinetic Type", "AI"),
    ("AI 3D Text", "AI"),
    ("AI Extrude", "AI"),
    ("AI Bevel Text", "AI"),
    ("AI Reflect", "AI"),
    ("AI Environment Map", "AI"),
    ("AI IBL", "AI"),
    ("AI AO Bake", "AI"),
    ("AI Normal Map", "AI"),
    ("AI Height Map", "AI"),
    ("AI Displacement", "AI"),
    ("AI PBR Preview", "AI"),
    ("AI Subsurface", "AI"),
    ("AI Caustics", "AI"),
    ("AI Volumetrics", "AI"),
    ("AI Fog", "AI"),
    ("AI God Rays", "AI"),
    ("AI Rain", "AI"),
    ("AI Snow", "AI"),
    ("AI Fire", "AI"),
    ("AI Smoke", "AI"),
    ("AI Sparks", "AI"),
    ("AI Lightning Pro", "AI"),
    ("AI Ocean", "AI"),
    ("AI Fluid", "AI"),
    ("AI Cloth", "AI"),
    ("AI Rigid Body", "AI"),
    ("AI Soft Body", "AI"),
    ("AI Constraints", "AI"),
    ("AI Joints", "AI"),
    ("AI IK", "AI"),
    ("AI Walk Cycle", "AI"),
    ("AI Mocap Clean", "AI"),
    ("AI Retarget", "AI"),
    ("AI Foot Lock", "AI"),
    ("AI Hand IK", "AI"),
    ("AI Look At", "AI"),
    ("AI Aim", "AI"),
    ("AI Orbit", "AI"),
    ("AI Dolly", "AI"),
    ("AI Crane", "AI"),
    ("AI Handheld", "AI"),
    ("AI Drone Path", "AI"),
    ("AI Car Rig", "AI"),
    ("AI Product Spin", "AI"),
    ("AI Turntable", "AI"),
    ("AI Packshot", "AI"),
    ("AI Packshot Lighting", "AI"),
    ("AI Macro Stack", "AI"),
    ("AI Focus Stack", "AI"),
    ("AI HDR Stack", "AI"),
    ("AI Panorama Stitch", "AI"),
    ("AI 360 Stitch", "AI"),
    ("AI Tiny Planet", "AI"),
    ("AI Dome Master", "AI"),
    ("AI Stereo 3D", "AI"),
    ("AI Depth Map Export", "AI"),
    ("AI Normals Export", "AI"),
    ("AI Point Cloud", "AI"),
    ("AI Mesh Reconstruct", "AI"),
    ("AI Photogrammetry", "AI"),
    ("AI NeRF Preview", "AI"),
    ("AI Gaussian Splat", "AI"),
    ("AI USD Stage", "AI"),
    ("AI glTF Preview", "AI"),
    ("AI FBX Import", "AI"),
    ("AI OBJ Import", "AI"),
    ("AI Alembic", "AI"),
    ("AI Sequence Geo", "AI"),
    ("AI Instancing", "AI"),
    ("AI LOD", "AI"),
    ("AI Culling", "AI"),
    ("AI Occlusion", "AI"),
    ("AI Shadow Catcher", "AI"),
    ("AI Matte Shadow", "AI"),
    ("AI Reflection Matte", "AI"),
    ("AI Cryptomatte", "AI"),
    ("AI Object ID", "AI"),
    ("AI Material ID", "AI"),
    ("AI UV Pass", "AI"),
    ("AI World Position", "AI"),
    ("AI Z-Depth", "AI"),
    ("AI Velocity Vectors", "AI"),
    ("AI Motion Vectors", "AI"),
    ("AI Beauty Pass", "AI"),
    ("AI Diffuse", "AI"),
    ("AI Specular", "AI"),
    ("AI Roughness", "AI"),
    ("AI Metalness", "AI"),
    ("AI Emission", "AI"),
    ("AI Ambient Occlusion", "AI"),
    ("AI Bent Normal", "AI"),
    ("AI Curvature", "AI"),
    ("AI Thickness", "AI"),
    ("AI ID Matte", "AI"),
    ("AI Holdout", "AI"),
    ("AI Shadow Pass", "AI"),
    ("AI Reflection Pass", "AI"),
    ("AI Refraction Pass", "AI"),
    ("AI Volume Pass", "AI"),
    ("AI Atmosphere Pass", "AI"),
    ("AI Z-Fog", "AI"),
    ("AI Light Groups", "AI"),
    ("AI AOV Manager", "AI"),
    ("AI Render Layers", "AI"),
    ("AI Takes", "AI"),
    ("AI Variants", "AI"),
    ("AI Version Stack", "AI"),
    ("AI Compare A/B", "AI"),
    ("AI Wipe Compare", "AI"),
    ("AI Split View", "AI"),
    ("AI Reference Lock", "AI"),
    ("AI Client Review", "AI"),
    ("AI Notes", "AI"),
    ("AI Markers AI", "AI"),
    ("AI Chaptering", "AI"),
    ("AI Thumbnail Grid", "AI"),
    ("AI Story Arc", "AI"),
    ("AI Beat Sheet", "AI"),
    ("AI Script Assist", "AI"),
    ("AI Voiceover", "AI"),
    ("AI Dub", "AI"),
    ("AI Lip Sync Hint", "AI"),
    ("AI Foley Suggest", "AI"),
    ("AI Room Tone", "AI"),
    ("AI Dialog Isolate", "AI"),
    ("AI Wind Reduce", "AI"),
    ("AI Plosive Fix", "AI"),
    ("AI De-Esser", "AI"),
    ("AI De-Click", "AI"),
    ("AI De-Crackle", "AI"),
    ("AI Hum Remove", "AI"),
    ("AI Spectral Repair", "AI"),
    ("AI Phase Repair", "AI"),
    ("AI Mono Downmix", "AI"),
    ("AI Stereo Width", "AI"),
    ("AI Mid-Side", "AI"),
    ("AI Haas", "AI"),
    ("AI Delay Throw", "AI"),
    ("AI Reverb Match", "AI"),
    ("AI IR Capture", "AI"),
    ("AI Convolution Reverb", "AI"),
    ("AI Algorithmic Reverb", "AI"),
    ("AI Spring Reverb", "AI"),
    ("AI Plate Reverb", "AI"),
    ("AI Hall", "AI"),
    ("AI Chamber", "AI"),
    ("AI Room", "AI"),
    ("AI Plate", "AI"),
    ("AI Shimmer", "AI"),
    ("AI Granular", "AI"),
    ("AI Resonator", "AI"),
    ("AI Ring Mod", "AI"),
    ("AI Bitcrush", "AI"),
    ("AI Sample Rate Reduce", "AI"),
    ("AI Tape Saturation", "AI"),
    ("AI Tube Saturation", "AI"),
    ("AI Transistor", "AI"),
    ("AI Console", "AI"),
    ("AI Bus Glue", "AI"),
    ("AI Master Bus", "AI"),
    ("AI Limiter", "AI"),
    ("AI Maximizer", "AI"),
    ("AI Clipper", "AI"),
    ("AI Brickwall", "AI"),
    ("AI True Peak Limiter", "AI"),
    ("AI Loudness Normalize", "AI"),
    ("AI EBU R128", "AI"),
    ("AI ATSC A/85", "AI"),
    ("AI CALM Act", "AI"),
    ("AI Netflix Deliverable", "AI"),
    ("AI IMF Package", "AI"),
    ("AI DCP Hint", "AI"),
    ("AI Broadcast Safe", "AI"),
    ("AI Gamut Clip", "AI"),
    ("AI Banding Fix", "AI"),
    ("AI Compression Artifact", "AI"),
    ("AI Mosquito NR", "AI"),
    ("AI Block NR", "AI"),
    ("AI Ringing Fix", "AI"),
    ("AI Sharpen AI Safe", "AI"),
    ("AI Upscale Edge", "AI"),
    ("AI Face Enhance", "AI"),
    ("AI Eye Enhance", "AI"),
    ("AI Teeth Whiten", "AI"),
    ("AI Skin Smooth", "AI"),
    ("AI Skin Tone", "AI"),
    ("AI Hair Detail", "AI"),
    ("AI Fabric Detail", "AI"),
    ("AI Texture Enhance", "AI"),
    ("AI Micro-Contrast", "AI"),
    ("AI Clarity", "AI"),
    ("AI Structure", "AI"),
    ("AI Haze Remove", "AI"),
    ("AI Dehaze", "AI"),
    ("AI Sky Enhance", "AI"),
    ("AI Foliage Pop", "AI"),
    ("AI Water Enhance", "AI"),
    ("AI Skin Mask", "AI"),
    ("AI Sky Mask", "AI"),
    ("AI Subject Mask", "AI"),
    ("AI Depth Aware Blur", "AI"),
    ("AI Bokeh", "AI"),
    ("AI Anamorphic Bokeh", "AI"),
    ("AI Cat Eye", "AI"),
    ("AI Lens Baby", "AI"),
    ("AI Tilt Shift", "AI"),
    ("AI Miniature", "AI"),
    ("AI Diorama", "AI"),
    ("AI Toy Camera", "AI"),
    ("AI Holga", "AI"),
    ("AI Polaroid", "AI"),
    ("AI Instant Film", "AI"),
    ("AI 35mm Gate", "AI"),
    ("AI 16mm Gate", "AI"),
    ("AI 8mm Gate", "AI"),
    ("AI Sprocket Holes", "AI"),
    ("AI Film Perf", "AI"),
    ("AI Gate Weave", "AI"),
    ("AI Film Flicker", "AI"),
    ("AI Projector Shake", "AI"),
    ("AI Dust Overlay", "AI"),
    ("AI Hair in Gate", "AI"),
    ("AI Scratch Overlay", "AI"),
    ("AI Vinegar Syndrome", "AI"),
    ("AI Bleach Bypass", "AI"),
    ("AI Cross Process", "AI"),
    ("AI Push Process", "AI"),
    ("AI Pull Process", "AI"),
    ("AI Technicolor 2 Strip", "AI"),
    ("AI Technicolor 3 Strip", "AI"),
    ("AI Kodachrome", "AI"),
    ("AI Ektachrome", "AI"),
    ("AI Fujifilm", "AI"),
    ("AI Agfa", "AI"),
    ("AI Ilford", "AI"),
    ("AI Polaroid Fade", "AI"),
    ("AI Sepia", "AI"),
    ("AI Cyanotype", "AI"),
    ("AI Duotone Split", "AI"),
    ("AI Monochrome", "AI"),
    ("AI Infrared Sim", "AI"),
    ("AI Night Vision", "AI"),
    ("AI Thermal", "AI"),
    ("AI X-Ray Stylize", "AI"),
    ("AI Blueprint", "AI"),
    ("AI Sketch", "AI"),
    ("AI Pencil", "AI"),
    ("AI Ink", "AI"),
    ("AI Watercolor", "AI"),
    ("AI Oil Paint", "AI"),
    ("AI Impasto", "AI"),
    ("AI Pointillize", "AI"),
    ("AI Halftone", "AI"),
    ("AI Newsprint", "AI"),
    ("AI Comic", "AI"),
    ("AI Posterize Art", "AI"),
    ("AI Stencil", "AI"),
    ("AI Edge Detect Art", "AI"),
    ("AI Kuwahara", "AI"),
    ("AI Bilateral", "AI"),
    ("AI Guided Filter", "AI"),
    ("AI Surface Blur", "AI"),
    ("AI Smart Sharpen", "AI"),
    ("AI High Pass", "AI"),
    ("AI Clarity Mix", "AI"),
    ("AI Frequency Sep", "AI"),
    ("AI Dodge Burn", "AI"),
    ("AI Zone System", "AI"),
    ("AI Histogram Paint", "AI"),
    ("AI Curves Auto", "AI"),
    ("AI Color Wheels Auto", "AI"),
    ("AI Shot Match", "AI"),
    ("AI Scene Balance", "AI"),
    ("AI Auto WB", "AI"),
    ("AI Skin Line", "AI"),
    ("AI Vector Scope Assist", "AI"),
    ("AI Waveform Assist", "AI"),
    ("AI False Color Assist", "AI"),
    ("AI Parade Assist", "AI"),
    ("AI HDR Histogram", "AI"),
    ("AI PQ Curve", "AI"),
    ("AI HLG Curve", "AI"),
    ("AI Dolby Vision Hint", "AI"),
    ("AI HDR10+ Hint", "AI"),
    ("AI SDR Downmap", "AI"),
    ("AI Tone Map", "AI"),
    ("AI Exposure Fusion HDR", "AI"),
    ("AI Ghost Removal HDR", "AI"),
    ("AI Deghost HDR", "AI"),
    ("AI Motion HDR", "AI"),
    ("AI Multi Cam Sync", "AI"),
    ("AI Audio Sync", "AI"),
    ("AI Timecode Sync", "AI"),
    ("AI Drift Fix", "AI"),
    ("AI Pullup Pulldown", "AI"),
    ("AI Telecine", "AI"),
    ("AI Inverse Telecine", "AI"),
    ("AI Frame Rate Conv", "AI"),
    ("AI Optical Flow", "AI"),
    ("AI Frame Blend HQ", "AI"),
    ("AI Morph Cut", "AI"),
    ("AI Seamless Loop", "AI"),
    ("AI Loop Crossfade", "AI"),
    ("AI Beat Loop", "AI"),
    ("AI Remix Music", "AI"),
    ("AI Extend Music", "AI"),
    ("AI Stem Isolate", "AI"),
    ("AI Drum Stem", "AI"),
    ("AI Bass Stem", "AI"),
    ("AI Vocal Stem", "AI"),
    ("AI Harmony Stem", "AI"),
    ("AI Melody Stem", "AI"),
    ("AI SFX Stem", "AI"),
    ("AI Room Tone Gen", "AI"),
    ("AI Ambience Gen", "AI"),
    ("AI Wind Gen", "AI"),
    ("AI Rain Gen", "AI"),
    ("AI Crowd Gen", "AI"),
    ("AI Footsteps Gen", "AI"),
    ("AI Whoosh Gen", "AI"),
    ("AI Impact Gen", "AI"),
    ("AI Riser Gen", "AI"),
    ("AI Downer Gen", "AI"),
    ("AI Braam Gen", "AI"),
    ("AI Sub Drop", "AI"),
    ("AI Tick Tock", "AI"),
    ("AI Clock FX", "AI"),
    ("AI UI Beeps", "AI"),
    ("AI Glitch SFX", "AI"),
    ("AI Digital Burst", "AI"),
    ("AI Analog Burst", "AI"),
    ("AI Tape Stop", "AI"),
    ("AI Vinyl Stop", "AI"),
    ("AI DJ Scratch", "AI"),
    ("AI Stutter Edit", "AI"),
    ("AI Beat Repeat", "AI"),
    ("AI Gater", "AI"),
    ("AI Trance Gate", "AI"),
    ("AI Sidechain Pump", "AI"),
    ("AI Ducking", "AI"),
    ("AI Auto Duck", "AI"),
    ("AI Voice Duck", "AI"),
    ("AI Music Duck", "AI"),
    ("AI Podcast Mix", "AI"),
    ("AI YouTube Loud", "AI"),
    ("AI TikTok Loud", "AI"),
    ("AI Instagram Loud", "AI"),
    ("AI Podcast Loud", "AI"),
    ("AI Audiobook Loud", "AI"),
    ("AI Game Loud", "AI"),
    ("AI Trailer Loud", "AI"),
    ("AI Cinema Loud", "AI"),
    ("AI Broadcast Loud", "AI"),
    ("AI Streaming Loud", "AI"),
    ("AI Vinyl Master", "AI"),
    ("AI Cassette Master", "AI"),
    ("AI Tape Hiss", "AI"),
    ("AI Vinyl Crackle", "AI"),
    ("AI Needle Drop", "AI"),
    ("AI Start Runout", "AI"),
    ("AI End Runout", "AI"),
    ("AI Inner Groove", "AI"),
    ("AI Wow Flutter", "AI"),
    ("AI Azimuth", "AI"),
    ("AI Head Bump", "AI"),
    ("AI Crosstalk", "AI"),
    ("AI Print Through", "AI"),
    ("AI Tape Saturation MS", "AI"),
    ("AI Console Color", "AI"),
    ("AI Bus Color", "AI"),
    ("AI Mix Bus Glue", "AI"),
    ("AI Mastering Chain", "AI"),
    ("AI Reference Match", "AI"),
    ("AI A/B Loudness", "AI"),
    ("AI LUFS Target", "AI"),
    ("AI Peak Target", "AI"),
    ("AI Dynamic Range", "AI"),
    ("AI Crest Factor", "AI"),
    ("AI Punch", "AI"),
    ("AI Transient Designer", "AI"),
    ("AI Attack Shaper", "AI"),
    ("AI Sustain Shaper", "AI"),
    ("AI Body Shaper", "AI"),
    ("AI Snap Clap Enhance", "AI"),
    ("AI Kick Enhance", "AI"),
    ("AI Snare Enhance", "AI"),
    ("AI HiHat Enhance", "AI"),
    ("AI Cymbal Smooth", "AI"),
    ("AI Tom Ring", "AI"),
    ("AI Room Ring", "AI"),
    ("AI Reverb Tail Trim", "AI"),
    ("AI Silence Trim", "AI"),
    ("AI Breath Trim", "AI"),
    ("AI Mouth Click", "AI"),
    ("AI Lip Smack", "AI"),
    ("AI Sibilance Guard", "AI"),
    ("AI Plosive Guard", "AI"),
    ("AI Room Tone Fill", "AI"),
    ("AI Noise Print", "AI"),
    ("AI Spectral Decompose", "AI"),
    ("AI Harmonic Exciter", "AI"),
    ("AI Air Band", "AI"),
    ("AI Presence", "AI"),
    ("AI Clarity Voice", "AI"),
    ("AI Warmth", "AI"),
    ("AI Body Voice", "AI"),
    ("AI Proximity", "AI"),
    ("AI De-Reverb", "AI"),
    ("AI De-Echo", "AI"),
    ("AI De-Box", "AI"),
    ("AI De-Honk", "AI"),
    ("AI De-Boom", "AI"),
    ("AI De-Harsh", "AI"),
    ("AI De-Sibilance", "AI"),
    ("AI De-Breath", "AI"),
    ("AI De-Mouth", "AI"),
    ("AI De-Lip", "AI"),
    ("AI De-Click Pro", "AI"),
    ("AI De-Crackle Pro", "AI"),
    ("AI De-Hum Pro", "AI"),
    ("AI De-Buzz", "AI"),
    ("AI De-Rumble", "AI"),
    ("AI De-Wind", "AI"),
    ("AI De-Rustle", "AI"),
    ("AI De-Cloth", "AI"),
    ("AI De-Fans", "AI"),
    ("AI De-AC", "AI"),
    ("AI De-Fridge", "AI"),
    ("AI De-Car", "AI"),
    ("AI De-Traffic", "AI"),
    ("AI De-Bird", "AI"),
    ("AI De-Dog", "AI"),
    ("AI De-Crowd", "AI"),
    ("AI Isolate Voice", "AI"),
    ("AI Isolate Music", "AI"),
    ("AI Isolate SFX", "AI"),
    ("AI Dialogue Boost", "AI"),
    ("AI Music Bed Duck", "AI"),
    ("AI Sidechain Voice", "AI"),
    ("AI Podcast Chain", "AI"),
    ("AI Broadcast Chain", "AI"),
    ("AI Cinema Chain", "AI"),
    ("AI Game Chain", "AI"),
    ("AI VR Audio", "AI"),
    ("AI Spatial Audio", "AI"),
    ("AI Binaural", "AI"),
    ("AI HRTF", "AI"),
    ("AI Atmos Bed", "AI"),
    ("AI Object Audio", "AI"),
    ("AI Channel Bed", "AI"),
    ("AI 5.1 Downmix", "AI"),
    ("AI 7.1 Downmix", "AI"),
    ("AI Stereo Upmix", "AI"),
    ("AI Surround Upmix", "AI"),
    ("AI Center Extract", "AI"),
    ("AI LFE Sculpt", "AI"),
    ("AI Phantom Center", "AI"),
    ("AI Width Control", "AI"),
    ("AI Mono Compatibility", "AI"),
    ("AI Phase Correlation", "AI"),
    ("AI Polarity", "AI"),
    ("AI Delay Align", "AI"),
    ("AI Sample Align", "AI"),
    ("AI Sub Align", "AI"),
    ("AI Drum Align", "AI"),
    ("AI Vocal Align", "AI"),
    ("AI Multitrack Align", "AI"),
    ("AI Drift Correct", "AI"),
    ("AI Stretch Vocals", "AI"),
    ("AI Pitch Vocals", "AI"),
    ("AI Formant Preserve", "AI"),
    ("AI Melodyne Hint", "AI"),
    ("AI AutoTune Hint", "AI"),
    ("AI Quantize Vocals", "AI"),
    ("AI Tighten Drums", "AI"),
    ("AI Quantize Drums", "AI"),
    ("AI Humanize MIDI", "AI"),
    ("AI Groove Extract", "AI"),
    ("AI Groove Apply", "AI"),
    ("AI Swing", "AI"),
    ("AI Shuffle", "AI"),
    ("AI Push Pull", "AI"),
    ("AI Nudge Clips", "AI"),
    ("AI Ripple Trim", "AI"),
    ("AI Slip Trim", "AI"),
    ("AI Slide Trim", "AI"),
    ("AI Roll Edit", "AI"),
    ("AI Ripple Delete", "AI"),
    ("AI Close Gap", "AI"),
    ("AI Ripple Markers", "AI"),
    ("AI Snap Markers", "AI"),
    ("AI Marker Detect", "AI"),
    ("AI Chapter Markers", "AI"),
    ("AI Beat Markers", "AI"),
    ("AI Silence Markers", "AI"),
    ("AI Scene Markers", "AI"),
    ("AI Comment Markers", "AI"),
    ("AI Web Markers", "AI"),
    ("AI CD Track Markers", "AI"),
    ("AI Subclip", "AI"),
    ("AI Subsequence", "AI"),
    ("AI Nested Edit", "AI"),
    ("AI Compound Clip", "AI"),
    ("AI Multicam", "AI"),
    ("AI Angle Switch", "AI"),
    ("AI Sync Angle", "AI"),
    ("AI Color Match Angles", "AI"),
    ("AI Audio Match Angles", "AI"),
    ("AI Timecode Angles", "AI"),
    ("AI Proxy Angles", "AI"),
    ("AI Full Res", "AI"),
    ("AI Half Res", "AI"),
    ("AI Quarter Res", "AI"),
    ("AI Eighth Res", "AI"),
    ("AI Smart Proxy", "AI"),
    ("AI Render Cache", "AI"),
    ("AI Disk Cache Clean", "AI"),
    ("AI Purge All", "AI"),
    ("AI Purge RAM", "AI"),
    ("AI Purge Undo", "AI"),
    ("AI Save Increment", "AI"),
    ("AI Autosave Vault", "AI"),
    ("AI Crash Recovery", "AI"),
    ("AI Session Log", "AI"),
    ("AI Diagnostics", "AI"),
    ("AI GPU Trace", "AI"),
    ("AI CPU Trace", "AI"),
    ("AI Frame Time", "AI"),
    ("AI Dropped Frames", "AI"),
    ("AI Buffer Health", "AI"),
    ("AI Disk Health", "AI"),
    ("AI Network Health", "AI"),
    ("AI Cloud Sync", "AI"),
    ("AI Cloud Render", "AI"),
    ("AI Farm Queue", "AI"),
    ("AI Priority Boost", "AI"),
    ("AI Cost Estimate", "AI"),
    ("AI ETA", "AI"),
    ("AI Notify Done", "AI"),
    ("AI Email Report", "AI"),
    ("AI Slack Notify", "AI"),
    ("AI Webhook", "AI"),
    ("AI API Keys", "AI"),
    ("AI Model Select", "AI"),
    ("AI Temperature", "AI"),
    ("AI System Prompt", "AI"),
    ("AI Tool Router", "AI"),
    ("AI Safety Filter", "AI"),
    ("AI PII Redact", "AI"),
    ("AI Watermark", "AI"),
    ("AI Forensic", "AI"),
    ("AI Chain of Custody", "AI"),
    ("AI Legal Hold", "AI"),
    ("AI EDRM Export", "AI"),
    ("AI Hash Verify", "AI"),
    ("AI Checksum", "AI"),
    ("AI Manifest", "AI"),
    ("AI MHL", "AI"),
    ("AI C2PA", "AI"),
    ("AI Provenance", "AI"),
    ("AI Content Credentials", "AI"),
    ("AI Invisible Watermark", "AI"),
    ("AI Visible Watermark", "AI"),
    ("AI Burn-in TC", "AI"),
    ("AI Burn-in Filename", "AI"),
    ("AI Burn-in LUT", "AI"),
    ("AI Burn-in Subs", "AI"),
    ("AI Open Captions", "AI"),
    ("AI Closed Captions", "AI"),
    ("AI SCC Export", "AI"),
    ("AI STL Export", "AI"),
    ("AI VTT Export", "AI"),
    ("AI SRT Export", "AI"),
    ("AI TTML", "AI"),
    ("AI EBU-TT", "AI"),
    ("AI IMSC", "AI"),
    ("AI CEA-608", "AI"),
    ("AI CEA-708", "AI"),
    ("AI Teletext", "AI"),
    ("AI DVB Sub", "AI"),
    ("AI PGS", "AI"),
    ("AI ASS", "AI"),
    ("AI SSA", "AI"),
    ("AI Karaoke", "AI"),
    ("AI Lyrics", "AI"),
    ("AI Chord Chart", "AI"),
    ("AI Sheet Music OCR", "AI"),
    ("AI MIDI Extract", "AI"),
    ("AI Drum MIDI", "AI"),
    ("AI Bass MIDI", "AI"),
    ("AI Melody MIDI", "AI"),
    ("AI Chord MIDI", "AI"),
    ("AI Arpeggiator", "AI"),
    ("AI Sequencer", "AI"),
    ("AI Step Seq", "AI"),
    ("AI Euclidean", "AI"),
    ("AI Polyrhythm", "AI"),
    ("AI Poly Meter", "AI"),
    ("AI Tempo Map", "AI"),
    ("AI Tap Tempo", "AI"),
    ("AI Beat Grid", "AI"),
    ("AI Warp Grid", "AI"),
    ("AI Elastic Audio", "AI"),
    ("AI Varispeed", "AI"),
    ("AI Pitch Shift Musically", "AI"),
    ("AI Time Stretch Musically", "AI"),
    ("AI Formant Shift", "AI"),
    ("AI Robot Voice", "AI"),
    ("AI Whisper Voice", "AI"),
    ("AI Monster Voice", "AI"),
    ("AI Telephone Voice", "AI"),
    ("AI Radio Voice", "AI"),
    ("AI Announcer Voice", "AI"),
    ("AI Trailer Voice", "AI"),
    ("AI Voice Clone Hint", "AI"),
    ("AI Accent Reduce", "AI"),
    ("AI Accent Add", "AI"),
    ("AI Language ID", "AI"),
    ("AI Translate Subs", "AI"),
    ("AI Dub Lip Hint", "AI"),
    ("AI Face Dub", "AI"),
    ("AI Deepfake Guard", "AI"),
    ("AI Synthetic Detect", "AI"),
    ("AI Authenticity", "AI"),
    ("AI Consent Log", "AI"),
    ("AI Talent Release", "AI"),
    ("AI Usage Rights", "AI"),
    ("AI Music Clearance", "AI"),
    ("AI Stock Suggest", "AI"),
    ("AI Stock License", "AI"),
    ("AI Similar Clip", "AI"),
    ("AI Reverse Search", "AI"),
    ("AI Duplicate Detect", "AI"),
    ("AI Near Duplicate", "AI"),
    ("AI Shot Boundary", "AI"),
    ("AI Cut Detect", "AI"),
    ("AI Flash Detect", "AI"),
    ("AI Black Detect", "AI"),
    ("AI Freeze Detect", "AI"),
    ("AI Repeat Detect", "AI"),
    ("AI Logo Detect", "AI"),
    ("AI Text Detect", "AI"),
    ("AI QR Detect", "AI"),
    ("AI Blur Faces Auto", "AI"),
    ("AI Blur Plates Auto", "AI"),
    ("AI Redact PII Video", "AI"),
    ("AI Redact Screens", "AI"),
    ("AI Screen OCR", "AI"),
    ("AI Table OCR", "AI"),
    ("AI Chart OCR", "AI"),
    ("AI Equation OCR", "AI"),
    ("AI Code OCR", "AI"),
    ("AI Handwriting OCR", "AI"),
    ("AI Doc Scan", "AI"),
    ("AI Perspective Fix", "AI"),
    ("AI Dewarp Doc", "AI"),
    ("AI Denoise Scan", "AI"),
    ("AI Sharpen Scan", "AI"),
    ("AI Color Scan", "AI"),
    ("AI Binarize", "AI"),
    ("AI Threshold Scan", "AI"),
    ("AI Vectorize Scan", "AI"),
    ("AI SVG Export", "AI"),
    ("AI PDF Export", "AI"),
    ("AI PNG Sequence", "AI"),
    ("AI TIFF Sequence", "AI"),
    ("AI EXR Sequence", "AI"),
    ("AI DPX Sequence", "AI"),
    ("AI OpenEXR Multipart", "AI"),
    ("AI Cryptomatte EXR", "AI"),
    ("AI DWAA", "AI"),
    ("AI DWAB", "AI"),
    ("AI PIZ", "AI"),
    ("AI ZIP", "AI"),
    ("AI RLE", "AI"),
    ("AI B44", "AI"),
    ("AI Half Float", "AI"),
    ("AI Full Float", "AI"),
    ("AI ACEScg", "AI"),
    ("AI ACEScc", "AI"),
    ("AI ACEScct", "AI"),
    ("AI IDT", "AI"),
    ("AI ODT", "AI"),
    ("AI LMT", "AI"),
    ("AI AMF", "AI"),
    ("AI CLF", "AI"),
    ("AI CTL", "AI"),
    ("AI DCTL", "AI"),
    ("AI OFX Hint", "AI"),
    ("AI SPI Hint", "AI"),
    ("AI Baselight Hint", "AI"),
    ("AI Resolve Hint", "AI"),
    ("AI Premiere Hint", "AI"),
    ("AI FCP Hint", "AI"),
    ("AI Avid Hint", "AI"),
    ("AI Nuke Hint", "AI"),
    ("AI Fusion Hint", "AI"),
    ("AI Blender Hint", "AI"),
    ("AI Cinema4D Hint", "AI"),
    ("AI Houdini Hint", "AI"),
    ("AI Maya Hint", "AI"),
    ("AI 3ds Max Hint", "AI"),
    ("AI Unreal Hint", "AI"),
    ("AI Unity Hint", "AI"),
    ("AI Godot Hint", "AI"),
    ("AI WebGPU Hint", "AI"),
    ("AI Metal Hint", "AI"),
    ("AI Vulkan Hint", "AI"),
    ("AI DX12 Hint", "AI"),
    ("AI CUDA Hint", "AI"),
    ("AI ROCm Hint", "AI"),
    ("AI OpenCL Hint", "AI"),
    ("AI ONNX Runtime", "AI"),
    ("AI TensorRT", "AI"),
    ("AI CoreML", "AI"),
    ("AI OpenVINO", "AI"),
    ("AI DirectML", "AI"),
    ("AI NNAPI", "AI"),
    ("AI XNNPACK", "AI"),
    ("AI Quantize INT8", "AI"),
    ("AI Quantize FP16", "AI"),
    ("AI Sparsity", "AI"),
    ("AI Prune", "AI"),
    ("AI Distill", "AI"),
    ("AI LoRA", "AI"),
    ("AI Fine Tune", "AI"),
    ("AI Eval Harness", "AI"),
    ("AI Dataset Tag", "AI"),
    ("AI Active Learning", "AI"),
    ("AI Human Review Queue", "AI"),
    ("AI Confidence Map", "AI"),
    ("AI Uncertainty", "AI"),
    ("AI Explainability", "AI"),
    ("AI Attention Viz", "AI"),
    ("AI Saliency Map", "AI"),
    ("AI Heatmap", "AI"),
    ("AI Gaze Estimate", "AI"),
    ("AI Aesthetic Score", "AI"),
    ("AI Technical QC", "AI"),
    ("AI QC Report PDF", "AI"),
    ("AI QC CSV", "AI"),
    ("AI QC JSON", "AI"),
    ("AI EBU R128 Scan", "AI"),
    ("AI PSE Check", "AI"),
    ("AI Photosensitive", "AI"),
    ("AI Safe Area QC", "AI"),
    ("AI Legal Text QC", "AI"),
    ("AI Spelling QC", "AI"),
    ("AI Grammar QC", "AI"),
    ("AI Brand Guideline", "AI"),
    ("AI Color Guideline", "AI"),
    ("AI Font Guideline", "AI"),
    ("AI Logo Guideline", "AI"),
    ("AI Lower Third Guideline", "AI"),
    ("AI End Card", "AI"),
    ("AI Bumper", "AI"),
    ("AI Slate", "AI"),
    ("AI Countdown", "AI"),
    ("AI Leader", "AI"),
    ("AI Tail Leader", "AI"),
    ("AI Academy Leader", "AI"),
    ("AI SMPTE Color Bars", "AI"),
    ("AI EBU Bars", "AI"),
    ("AI ARIB Bars", "AI"),
    ("AI PLUGE", "AI"),
    ("AI Multi Burst", "AI"),
    ("AI Focus Chart", "AI"),
    ("AI Resolution Chart", "AI"),
    ("AI Zone Plate", "AI"),
    ("AI Siemens Star", "AI"),
    ("AI Distortion Grid", "AI"),
    ("AI Chromatic Chart", "AI"),
    ("AI Macbeth Chart", "AI"),
    ("AI ColorChecker", "AI"),
    ("AI Skin Chip", "AI"),
    ("AI Gray Ramp", "AI"),
    ("AI IRE Steps", "AI"),
    ("AI Waveform Generator", "AI"),
    ("AI Sync Pulse", "AI"),
    ("AI Pilot Tone", "AI"),
    ("AI LTC Generate", "AI"),
    ("AI VITC", "AI"),
    ("AI Ancillary Data", "AI"),
    ("AI Timecode Burn", "AI"),
    ("AI Filename Burn", "AI"),
    ("AI Metadata Burn", "AI"),
    ("AI GPS Burn", "AI"),
    ("AI Lens Burn", "AI"),
    ("AI Camera Burn", "AI"),
    ("AI ISO Shutter Burn", "AI"),
    ("AI T-stop Burn", "AI"),
    ("AI White Balance Burn", "AI"),
    ("AI LUT Name Burn", "AI"),
    ("AI CDL Burn", "AI"),
    ("AI ASC CDL", "AI"),
    ("AI CCC", "AI"),
    ("AI CSL", "AI"),
    ("AI CLF LUT", "AI"),
    ("AI 1D LUT", "AI"),
    ("AI 3D LUT", "AI"),
    ("AI Tetrahedral", "AI"),
    ("AI Trilinear", "AI"),
    ("AI Nearest LUT", "AI"),
    ("AI LUT Size", "AI"),
    ("AI Shaper LUT", "AI"),
    ("AI Pre-shaper", "AI"),
    ("AI Post-shaper", "AI"),
    ("AI Cube LUT", "AI"),
    ("AI Panasonic LUT", "AI"),
    ("AI Sony LUT", "AI"),
    ("AI Canon LUT", "AI"),
    ("AI ARRI LUT", "AI"),
    ("AI RED LUT", "AI"),
    ("AI BMD LUT", "AI"),
    ("AI Fuji LUT", "AI"),
    ("AI Nikon LUT", "AI"),
    ("AI DJI LUT", "AI"),
    ("AI GoPro LUT", "AI"),
    ("AI iPhone LUT", "AI"),
    ("AI Android LUT", "AI"),
    ("AI Webcam LUT", "AI"),
    ("AI Zoom LUT", "AI"),
    ("AI Teams LUT", "AI"),
    ("AI Meet LUT", "AI"),
    ("AI Skype LUT", "AI"),
    ("AI OBS LUT", "AI"),
    ("AI Stream LUT", "AI"),
    ("AI Game Capture LUT", "AI"),
    ("AI HDR Game", "AI"),
    ("AI SDR Game", "AI"),
    ("AI Ray Reconstruction", "AI"),
    ("AI DLSS Hint", "AI"),
    ("AI FSR Hint", "AI"),
    ("AI XeSS Hint", "AI"),
    ("AI TAA Fix", "AI"),
    ("AI Ghosting Fix", "AI"),
    ("AI Sharpen Game", "AI"),
    ("AI Denoise Game", "AI"),
    ("AI Upscaling Game", "AI"),
    ("AI Frame Gen Game", "AI"),
    ("AI Reflex Low Latency", "AI"),
    ("AI G-Sync Hint", "AI"),
    ("AI FreeSync Hint", "AI"),
    ("AI VRR Hint", "AI"),
    ("AI ALLM Hint", "AI"),
    ("AI QFT Hint", "AI"),
    ("AI HDMI Infoframe", "AI"),
    ("AI EDID Hint", "AI"),
    ("AI HDR Metadata", "AI"),
    ("AI SEI Parser", "AI"),
    ("AI HEVC SEI", "AI"),
    ("AI AV1 Metadata", "AI"),
    ("AI VP9 Metadata", "AI"),
    ("AI ProRes Metadata", "AI"),
    ("AI DNx Metadata", "AI"),
    ("AI EXR Metadata", "AI"),
    ("AI TIFF Metadata", "AI"),
    ("AI RAW Decode", "AI"),
    ("AI Bayer Debayer", "AI"),
    ("AI X-Trans", "AI"),
    ("AI Foveon", "AI"),
    ("AI Dual ISO", "AI"),
    ("AI HDR Merge RAW", "AI"),
    ("AI Lens Correction RAW", "AI"),
    ("AI Chromatic Aberration RAW", "AI"),
    ("AI Vignette RAW", "AI"),
    ("AI Denoise RAW", "AI"),
    ("AI Sharpen RAW", "AI"),
    ("AI Detail RAW", "AI"),
    ("AI Moire RAW", "AI"),
    ("AI False Color RAW", "AI"),
    ("AI Zebra RAW", "AI"),
    ("AI Waveform RAW", "AI"),
    ("AI Histogram RAW", "AI"),
    ("AI Clipping RAW", "AI"),
    ("AI Highlight Roll", "AI"),
    ("AI Shadow Lift", "AI"),
    ("AI Midtone Pivot", "AI"),
    ("AI S-Curve", "AI"),
    ("AI Film Curve", "AI"),
    ("AI Log Curve", "AI"),
    ("AI PQ OOTF", "AI"),
    ("AI HLG OOTF", "AI"),
    ("AI SDR Gamma", "AI"),
    ("AI BT1886", "AI"),
    ("AI sRGB", "AI"),
    ("AI Display P3", "AI"),
    ("AI Rec709", "AI"),
    ("AI Rec2020", "AI"),
    ("AI P3 D65", "AI"),
    ("AI P3 DCI", "AI"),
    ("AI DCI XYZ", "AI"),
    ("AI ACES AP0", "AI"),
    ("AI ACES AP1", "AI"),
    ("AI DaVinci WG", "AI"),
    ("AI ARRI WG", "AI"),
    ("AI Canon WG", "AI"),
    ("AI Sony SGamut", "AI"),
    ("AI RED WG", "AI"),
    ("AI BMD WG", "AI"),
    ("AI Fuji WG", "AI"),
    ("AI Nikon WG", "AI"),
    ("AI DJI WG", "AI"),
    ("AI GoPro WG", "AI"),
    ("AI iPhone WG", "AI"),
    ("AI Hybrid Log Gamma", "AI"),
    ("AI PQ ST2084", "AI"),
    ("AI Dolby Vision CM", "AI"),
    ("AI HDR10+", "AI"),
    ("AI SL-HDR", "AI"),
    ("AI Advanced HDR", "AI"),
    ("AI BBC HLG", "AI"),
    ("AI NHK HDR", "AI"),
    ("AI ARIB STD-B67", "AI"),
    ("AI China HDR", "AI"),
    ("AI India HDR", "AI"),
    ("AI Korea HDR", "AI"),
    ("AI Japan HDR", "AI"),
    ("AI EU HDR", "AI"),
    ("AI US HDR", "AI"),
    ("AI UK HDR", "AI"),
    ("AI AU HDR", "AI"),
    ("AI NZ HDR", "AI"),
    ("AI CA HDR", "AI"),
    ("AI MX HDR", "AI"),
    ("AI BR HDR", "AI"),
    ("AI AR HDR", "AI"),
    ("AI CL HDR", "AI"),
    ("AI CO HDR", "AI"),
    ("AI PE HDR", "AI"),
    ("AI ZA HDR", "AI"),
    ("AI EG HDR", "AI"),
    ("AI NG HDR", "AI"),
    ("AI KE HDR", "AI"),
    ("AI GH HDR", "AI"),
    ("AI MA HDR", "AI"),
    ("AI TN HDR", "AI"),
    ("AI DZ HDR", "AI"),
    ("AI LY HDR", "AI"),
    ("AI SD HDR", "AI"),
    ("AI ET HDR", "AI"),
    ("AI SO HDR", "AI"),
    ("AI DJ HDR", "AI"),
    ("AI ER HDR", "AI"),
    ("AI SS HDR", "AI"),
    ("AI UG HDR", "AI"),
    ("AI RW HDR", "AI"),
    ("AI BI HDR", "AI"),
    ("AI MW HDR", "AI"),
    ("AI ZM HDR", "AI"),
    ("AI ZW HDR", "AI"),
    ("AI BW HDR", "AI"),
    ("AI NA HDR", "AI"),
    ("AI SZ HDR", "AI"),
    ("AI LS HDR", "AI"),
    ("AI LR HDR", "AI"),
    ("AI MR HDR", "AI"),
    ("AI GM HDR", "AI"),
    ("AI GW HDR", "AI"),
    ("AI GN HDR", "AI"),
    ("AI SL HDR", "AI"),
    ("AI LR HDR2", "AI"),
    ("AI Panel Overflow A", "AI"),
    ("AI Panel Overflow B", "AI"),
    ("AI Panel Overflow C", "AI"),
]


def main() -> None:
    rows: list[tuple[int, str, str]] = []
    pid = 0
    for name, cat in WIRED:
        rows.append((pid, name, cat))
        pid += 1
    for name, cat in EXTRA:
        rows.append((pid, name, cat))
        pid += 1

    out = Path(__file__).resolve().parents[1] / "src" / "ui" / "panels" / "PanelRegistry.qml"
    lines: list[str] = [
        "// AUTO-GENERATED by tools/gen_panel_registry.py — do not hand-edit.",
        "import QtQuick",
        "",
        "QtObject {",
        "    id: root",
        "    // Flat catalog for EditorWindow: { id, name, category }",
        "    readonly property var panels: [",
    ]
    for i, name, cat in rows:
        # QML string escaping
        ns = name.replace("\\", "\\\\").replace('"', '\\"')
        cs = cat.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'        {{ id: {i}, name: "{ns}", category: "{cs}" }},')
    lines.append("    ]")
    lines.append("}")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(rows)} panels -> {out}")


if __name__ == "__main__":
    main()
